### ISSUE TITLE
Auto height doesn't work as expected

### ISSUE THREAD

**Issue by frederickfogerty** [souporserious/react-motion-ui-pack#16]
Hey, I've created this branch to (badly) demonstrate what I mean: https://github.com/frederickfogerty/react-motion-ui-pack/tree/height-auto-example

First off, in the example, I can't get it to calculate the right auto height as much as I try, I assure you it works in my own project. Not sure if this is desired behaviour.

Secondly, and more majorly, when `height: 'auto'` is passed to Transition, it only animates the height after the previous 'animation' has 'finished'. That is, if we interrupt it, it will break, and height won't animate at all, often jumping to `0px`. This is shown in the example.

This doesn't happen when height is set to a set value, of course.

Other than this I have no qualms with this library, thanks!

**Comment by souporserious** [comment]
Crap. Thanks for the feedback auto height is hard. I'll look into it and see what I can do. Open to any help/suggestions.

**Comment by nkbt** [comment]
This should fix the issue.

https://www.npmjs.com/package/react-collapse

**Comment by frederickfogerty** [comment]
@nkbt that looks good - maybe we could integrate some of that logic here

**Comment by nkbt** [comment]
It is a small component, just add as dep

**Comment by souporserious** [comment]
Yeah planning on ripping out what I did and use @nkbt's component for auto height instead :) should be able to get to it this weekend.

**Comment by nkbt** [comment]
@souporserious ping me if you need any help. And feel free to PR or open issues if you find any

**Comment by souporserious** [comment]
Fixed in this release https://github.com/souporserious/react-motion-ui-pack/commit/4faa3f0a47771e3e936d3d20f79c9b006addc7e4 please let me know if you notice anything else.
