### ISSUE TITLE
React 0.14 Support

### ISSUE THREAD

**Issue by frederickfogerty** [souporserious/react-motion-ui-pack#17]
Moving react out of deps seems to solve a few issues - I can't seem to nail down the others

**Comment by jprichardson** [comment]
> Moving react out of deps seems to solve a few issues - I can't seem to nail down the others

Yes, please remove React as a dependency. Maybe use `peerDependencies` for both? Desired behavior (won't install) for `peerDependencies` will be achieved with npm v3.

**Comment by frederickfogerty** [comment]
> for both

Both what? Do you mean `react-motion` as well?

**Comment by souporserious** [comment]
React 0.14.0 now supported in this commit https://github.com/souporserious/react-motion-ui-pack/commit/b1e3cff970e2979116a71dc9215a6ee6d5188c7f

**Comment by frederickfogerty** [comment]
:clap:
