### ISSUE TITLE
Allow custom spring parameters for "auto" sizing.  

### ISSUE THREAD

**Issue by chen-ye** [souporserious/react-motion-ui-pack#20]
Currently, the component only correctly animates to "auto" heights/widths if "auto" is passed into the height/width parameter.  This precludes using a custom spring to animate to these values without manually wrapping the subcomponents in a measure component.  

I made a quick and dirty fix in my fork (4daf23f6478a67fe903cbd7117e1110b2cd07b76 and 8a472e9b77cc03fa46b644026168e4a1323fdca0) which adds a "springParams" parameter, used to construct the spring for values that have autocreated springs.  

(The fork itself also has other modifications to make things work with meteor, but implementing this again would be fairly trivial)

**Comment by souporserious** [comment]
I will add this in the next release. Revamped the Measure component to get more accurate and reliable measurements for auto values. Once I get this in I will add in a spring config for auto values as well.

Also, in the future please use the src directory to make changes to files :) need to add a contributing section to the README

**Comment by chen-ye** [comment]
oh, i can write a proper pull request tonight

this was just a quick fork for my own project, and is contaminated with some other changes too.

**Comment by souporserious** [comment]
Fixed in this release https://github.com/souporserious/react-motion-ui-pack/commit/4faa3f0a47771e3e936d3d20f79c9b006addc7e4 please let me know if you notice anything else.
