### ISSUE TITLE
Are all values wrapped in `spring()` as default?

### ISSUE THREAD

**Issue by gmaclennan** [souporserious/react-motion-ui-pack#22]
I'm not quite clear from the `README.md`, but am I correct in thinking that all style values passed to `enter` and `leave` are wrapped in `spring()` by default? I am assuming that there is no way to jump immediately to any style values on enter or leave, since all style properties are animated?

**Comment by frederickfogerty** [comment]
Yes, that's correct. I imagine this was to be consistent with the old api. With the old api you could also just have a spring config of `[]`, I'm not sure if this still works. This is definitely something we need to look at, thanks.

**Comment by souporserious** [comment]
Yes, they are automatically wrapped with a spring. I wanted to keep the API really simple and easy to use. But maybe I'll remove that to keep it more inline with React Motion. @gmaclennan what is your use case for immediately jumping values? Yeah passing an empty config still won't immediately jump to the value right now, I need to look into that.

**Comment by gmaclennan** [comment]
Not sure there is a use-case actually, it was just initially confusing coming from React-motion until I looked through the code. Would be good to clarify these defaults in the README

**Comment by souporserious** [comment]
Definitely, I can see how that's confusing. I'll leave this open until I get a fix on the empty config, as well as README updated. Thanks for the feedback :)

**Comment by souporserious** [comment]
README updated https://github.com/souporserious/react-motion-ui-pack/commit/2bfbe0f61990ef63f000829badae2c1a8a7499b1

**Comment by frederickfogerty** [comment]
@souporserious I vote to close this and just make consumers use `spring` to animate their values

**Comment by souporserious** [comment]
I am closing this in favor of keeping the API simple. Please use React Motion directly for advance use.
