### ISSUE TITLE
Support nested `Transition`

### ISSUE THREAD

**Issue by filod** [souporserious/react-motion-ui-pack#23]
I embed a `onlyChild` (component={false} in new version) `Transition` component in a normal list `Transition` like

``` javascript
<Transition
  className="content-blocks"
  component={'div'}
  enter={{
    height: 'auto',
    opacity: 1,
  }}
  leave={{
    height: 0,
    opacity: 0,
  }}
>
  {blocks.map((block, i)=>{
    let trash = <Transition
      onlyChild
      enter={{width: 32, margin: 5, padding: 2}}
      leave={{width: 0, margin: 0, padding: 0}}
    >
      {editMode && <button
        key="trash"
        style={{overflow: 'hidden'}}
        className="btn btn-icon"
        onClick={this.removeBlock.bind(this, block)}>
        <span className="icon icon-trash"></span>
      </button>}
    </Transition>
    if (block.__typename === 'TextBlock') {
      return <div className="editor-block-wrap" key={i}>
          <TextEditor block={block} />
          {trash}
        </div>
    } else if (block.__typename === 'VoiceBlock') {
      return <div className="editor-block-wrap" key={i}>
          <VoiceBlock block={block}
                      meta={block.__meta}
                      refreshing={this.state.refreshing}
                      onRefreshClick={::this.refresh} />
          {trash}
        </div>
    }
    return null // unsupported block type
  })}
</Transition>
```

~~when i change `editMode` to true, trash element's parent also change his height.~~
no matter the height is 'auto' or specific value, trash element's parent will change its height only if i set `editMode` to ture.
or it will not change his height (opacity is acting normal)

**Comment by souporserious** [comment]
Can you please be more descriptive? Is an error getting thrown when trying to nest Transitions?

Are you having a problem with nested `auto` heights specifically? If so, this is unfortunately unsupported right now. I'll do my best to get it fixed as soon as I can. Other styles should work fine when nested.

**Comment by filod** [comment]
@souporserious updated the description  :D

**Comment by souporserious** [comment]
Thank you. Can you try removing the `auto` height and tell if it works after that? I think that is the cause of the problem.

**Comment by filod** [comment]
updated

**Comment by souporserious** [comment]
Yeah so it seems to be an issue with the way auto height values are calculated, I'll look into this when I get a chance. Thanks for the descriptions :)

**Comment by filod** [comment]
yep, also have calc problem when in this structure:

```
<Flex>
  <div> box 1</div>
  <div> box 2</div>
</Flex>
```

Trasition seems only calculated the height of `box 2`

**Comment by souporserious** [comment]
Since auto height is so tedious it has been removed for now to focus on other parts of the library. Please feel free to look at the branch with auto height here https://github.com/souporserious/react-motion-ui-pack/tree/auto-height to help if you can or you can use my other library for non-transition height animation https://github.com/souporserious/react-fluid-container
