### ISSUE TITLE
Should assume `overflow: hidden` in transition ?

### ISSUE THREAD

**Issue by filod** [souporserious/react-motion-ui-pack#24]
see https://github.com/souporserious/react-motion-ui-pack/blob/master/src/Transition.jsx#L177

In my own case, i dont want element be 'overflow: hidden' in transition, because the child element's border will be clipped, like :
![image](https://cloud.githubusercontent.com/assets/679897/11114235/1ea1f0ee-895e-11e5-8eff-28da86ab504b.png)

**Comment by souporserious** [comment]
True. I will remove this in the next release. I did it because I want to say most use cases will need `overflow: hidden` with auto height, but I can integrate that into a `slideDown` preset :)

**Comment by filod** [comment]
that's a great choice

**Comment by souporserious** [comment]
Fixed :) https://github.com/souporserious/react-motion-ui-pack/commit/9740999525f94800dd85c37e437747f7baa08777
