### ISSUE TITLE
Breaks on server side rendering 

### ISSUE THREAD

**Issue by bobiblazeski** [souporserious/react-motion-ui-pack#26]
/node_modules/react-motion-ui-pack/lib/get-vendor-prefix.js:9
  if (!document) return prop;
       ^

ReferenceError: document is not defined

**Comment by 0m15** [comment]
same as #25

**Comment by souporserious** [comment]
This has been fixed https://github.com/souporserious/react-motion-ui-pack/commit/22a2776a2fe5b62932ea40c7c15a67fd964773fa I will push out an update ASAP. I'll close this issue once it's out.

**Comment by bobiblazeski** [comment]
Many thanks for the quick reply

**Comment by souporserious** [comment]
Fixed :) https://github.com/souporserious/react-motion-ui-pack/commit/991400d35dc5329ff0c74fbe3b866dc8251fecbc
