### ISSUE TITLE
Note about Height Transition

### ISSUE THREAD

**Issue by vramana** [souporserious/react-motion-ui-pack#27]
I think for the Height Transition to work the way it should, I have observed that the wrapping contianer needs to have `overflow: hidden`. Is this true? If so, I think you should add a note in the README.

A big thanks for this repo. Excellent Job.

**Comment by JoeMattie** [comment]
Excellent tip.  This just saved me a huge headache!

**Comment by frederickfogerty** [comment]
Yeah, this was removed in 9740999525, I'm not sure why - I can guess that it was because in some cases you might want to show the overflow.

**Comment by frederickfogerty** [comment]
Added to readme in de995e6b469
