### ISSUE TITLE
Height transition results in empty string

### ISSUE THREAD

**Issue by neverfox** [souporserious/react-motion-ui-pack#28]
Works (raw react-motion):

```
<Motion style={{ height : 88 }} defaultStyle={{ height : 0 }}>
  {value => <div style={{ backgroundColor : '#2196f3', height : value.height }} />}
</Motion>
```

Doesn't:

```
<Transition component={false} enter={{ height : 88 }} leave={{ height : 0 }}>
  <div style={{ backgroundColor : '#2196f3' }} />
</Transition>
```

Nothing happens and the resulting height is `""`. I haven't had problems with other cases that don't involve height, e.g. `paddingLeft` and `top`.

**Comment by frederickfogerty** [comment]
I can't immediately think of anything that could be causing, I'll have a look at this when I can.

**Comment by souporserious** [comment]
I'm currently tied up, but I will look into this as soon as I can and see what is wrong. Probably has to do with 'auto' height logic killing the value. Thank you for posting the issue @neverfox.

**Comment by souporserious** [comment]
Fixed https://github.com/souporserious/react-motion-ui-pack/blob/master/CHANGELOG.md#070
