### ISSUE TITLE
Slide in/out animation

### ISSUE THREAD

**Issue by svk31** [souporserious/react-motion-ui-pack#29]
This isn't really an issue with your library, but I'm hoping you can help me out.

I'm trying to do a simple "slide new content in from the right, slide old content out to the right" animation using your library, but what happens is the new content gets placed below the old content until the old content is removed from the dom, at which point the new content pops into the right position. Here's a gif that shows the effect:

http://g.recordit.co/hlk0fEyBEn.gif

Any ideas how I could solve this?

**Comment by tnrich** [comment]
+1

**Comment by souporserious** [comment]
Hmm you could possibly use `onEnter` to set the incoming to `position: absolute` so it's out of the flow, then hook into `onEnd` and determine when the final value has been reached and kill the absolute positioning.

Or...

Check out a react motion slider I've been working on https://github.com/souporserious/react-motion-slider for almost that exact same thing :)

**Comment by tnrich** [comment]
Cool stuff, how far along is your react-motion-slider?

**Comment by souporserious** [comment]
It's pretty close. The API is pretty solid now. You can pull the repo and run the same stuff as this one to get the local version working. I really just need to add touch/dragging support back in. The README is currently outdated but you can look in `/example` to see how it works.

**Comment by tnrich** [comment]
Sweet! Does it do left to right sliding for variable height divs also? That's the specific case I'm trying to hit

**Comment by svk31** [comment]
Thanks, I did consider doing something to that effect but wasn't quite sure how to go about it. I'll have another go tomorow and probably check out your slider library too.

**Comment by souporserious** [comment]
@tnrich yes it has an `autoHeight` prop, it just doesn't work well with vertical sliding right now.

**Comment by souporserious** [comment]
Closing this since it isn't an issue with this library please feel free to file anything over at the [react-motion-slider repo](https://github.com/souporserious/react-motion-slider).
