### ISSUE TITLE
missing prop "styles"

### ISSUE THREAD

**Issue by Ahrengot** [souporserious/react-motion-ui-pack#35]
When I copy/paste the example from the readme file:

``` JavaScript
<Transition
  component={false} // don't use a wrapping component
  enter={{
    opacity: 1,
    translateY: spring(0, {stiffness: 400, damping: 10})
  }}
  leave={{
    opacity: 0,
    translateY: 250
  }}
>
  {
    this.state.modalOpen &&
    <div key="modal" className="modal__content">
      // modal code
    </div>
  }
</Transition>
```

I get the following error:

> Warning: Failed propType: Required prop `styles` was not specified in `TransitionMotion`. Check the render method of `Transition`.

**Comment by Ahrengot** [comment]
Never mind, something funky was going on elsewhere. Sorry about that.

**Comment by dawidvdh** [comment]
@Ahrengot what was your issue? as i am having the same thing on my side... 

Any Help would be Greatly Appreciated.

**Comment by mb8z** [comment]
Same problem here. Any ideas?
