### ISSUE TITLE
Passing custom class as component

### ISSUE THREAD

**Issue by asvetliakov** [souporserious/react-motion-ui-pack#36]
Has passing only html tags as strings and {false} to  component prop of Transition been intended?

I'm trying to do something like:

``` jsx
class Menu extends React.Component {...}

class AnimatedMenu extends React.Component {
  render() {
    return (
      <Transition component={Menu} ...>...</Transition>
    );
  }
}
```

This works but gives me warning about incorrect prop types

**Comment by souporserious** [comment]
Hmm interesting, no it wasn't intended. I did not realize you could pass a custom component like that. Totally makes sense though. If you'd like to do a PR, I can review it and bring it in if all looks good. Should be just a PropType update correct?

**Comment by asvetliakov** [comment]
Yes should be just PropType update, however not sure if just React.PropTypes.element element will work or need a custom validator with checking for React.isValidElement().
I'll give a try
