### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by frederickfogerty** [souporserious/react-motion-ui-pack#38]
Currently the build always fails, this project needs a travis config.

**Comment by souporserious** [comment]
Do you know how Travis works and if so, can you help set that up? I set it up and never figured out the rest, been super busy lately.

**Comment by frederickfogerty** [comment]
Yeah I can have a bash at setting it up for you

**Comment by frederickfogerty** [comment]
@souporserious that's because there's nothing to test hahah. I'm going to add a linter for now
