### ISSUE TITLE
Transition component doesn't unmount nicely

### ISSUE THREAD

**Issue by Nimaear** [souporserious/react-motion-ui-pack#41]
When the `Transition` element gets unmounted while an enter animation is taking place, following warning is spammed:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the TransitionMotion component.
```

This can be easily reproduced by replacing the `ToDos` component in the example directory with next piece of code an press the 'Toggle' button randomly.

``` javascript
class ToDos extends Component {
  constructor(props) {
    super(props);
    this.state = { on: true, items: ['apples', 'oranges', 'bananas', 'pears', 'kiwis'] };
  }

  addItem() {
    let newItems = this.state.items.concat([prompt('Enter some text')]);
    this.setState({ items: newItems });
  }

  removeItem = (index) => {
    let newItems = this.state.items;
    newItems.splice(index, 1);
    this.setState({ items: newItems });
  }

  addRandom = () => {
    const add = Math.random() > 0.5;
    if (add) {
      let newItems = this.state.items.concat([Math.random()]);
      this.setState({ items: newItems });
    }
    setTimeout(this.addRandom, 400);
  }

  componentDidMount() {
    setTimeout(this.addRandom, 400);
  }

  toggle = () => {
    this.setState({on : !this.state.on});
  }



  render() {
    const items = this.state.items.map((item, index) => {
      return <Todo key={item} item={item} index={index} onDelete={this.removeItem} />
    });

    return (
      <div className="todo-app">
        <div className="buttons">
          <button onClick={this.addItem.bind(this)}>Add Item</button>
          <button onClick={this.toggle}>Toggle</button>
        </div>
        {this.state.on ? <Transition
          component="div"
          className="todos"
          measure={true}
          enter={{
            height: 'auto',
            scale: 1,
            translateY: 0,
            opacity: 1
          }}
          leave={{
            height: 0,
            scale: 0.5,
            translateY: 0,
            opacity: -1
          }}
        >
          {items}
        </Transition> : null}
      </div>
      );
  }
}
```

**Comment by souporserious** [comment]
Hmm I'm busy right now with my day job, but I'll look into this as soon as I can and get back to you. Thanks for posting the issue.

**Comment by Nimaear** [comment]
I looked a little more further into this. The thing is I can prevent this from happening by actually adjusting the componentWillUnmount and the RAF handler in react-motion. So I am actually not even sure this is a react-motion-ui-pack or a react-motion bug.

**Comment by souporserious** [comment]
I'm guessing it's an issue with this lib since state is kept in the component. Probably just need to do some sort of check to make sure the component hasn't been unmounted before updating state.

**Comment by souporserious** [comment]
@Nimaear were you able to look into this any further? I cleaned up a bunch and stopped setting state in the component to try and fix this issue but I can't figure out what exactly is causing it. I do know that if I don't use React Measure it does not throw that error. I'm wondering if it's something that should still be fixed in React Motion because of some weird edge case that causes it by using it with React Measure, but I'm not sure what to do.

**Comment by Nimaear** [comment]
Yes, I was actually able to look into it further and I believe the problem to be in react-motion. I just can't seem to be reproducing it in react-motion without react-motion-ui-pack though. I'll double check it once more this weekend and contact the author of react-motion.

**Comment by souporserious** [comment]
@Nimaear thanks for looking into this. Feel free to join us in the react-motion channel on Discord http://www.reactiflux.com/

**Comment by carbureted** [comment]
+1
