### ISSUE TITLE
Breaking error on startup

### ISSUE THREAD

**Issue by yogiben** [souporserious/react-motion-ui-pack#42]
After following install steps and running `npm run dev`, browser shows:

`Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by souporserious** [comment]
Weird. Things are working locally on my end. Can you try clearing your `node_modules` and trying `npm install` again? Please provide anymore information you can about the error, especially where it's coming from.

**Comment by mairh** [comment]
Getting the same error with the latest release.
<img width="1418" alt="screen shot 2016-03-02 at 12 07 23" src="https://cloud.githubusercontent.com/assets/4072250/13457163/5a5b3268-e06f-11e5-88d0-5e1c46fd578c.png">

**Comment by souporserious** [comment]
@frederickfogerty looks like the Travis integration broke everything. My bad for not testing that. I had assumed it was passing on your end.

**Comment by souporserious** [comment]
Everything is now back to normal I had to revert the last two PR's and force push. Please let me know if anything else comes up.
