### ISSUE TITLE
React 15 unitless number warning

### ISSUE THREAD

**Issue by kristian-puccio** [souporserious/react-motion-ui-pack#46]
Seems like React 15 is thowing an warning if you don't add a unit to the height style.

```
warning.js:44 Warning: a `div` tag (owner: `PanelContainer`) was passed a numeric string value for CSS property `height` (value: `0.0000`) which will be treated as a unitless number in a future version of React.
```

I guess we should just add px by default to the style but maybe it needs to be customisable to other units?

**Comment by souporserious** [comment]
Should just need `parseInt` or `+` operator since React still allows unitless numbers just not as strings I believe. I'll cut a new release with this fixed soon. Thanks for letting me know.

**Comment by kristian-puccio** [comment]
Great thanks!

**Comment by souporserious** [comment]
Fixed in the latest release :) https://github.com/souporserious/react-motion-ui-pack/commit/5dd44815677b12da975b2e564bc591c19e5e484b
