### ISSUE TITLE
isValidElement not defined

### ISSUE THREAD

**Issue by miracle2k** [souporserious/react-motion-ui-pack#50]
In this file:

https://github.com/souporserious/react-motion-ui-pack/blob/master/src/is-element.js

Occurs when passing an element to component:

```
 <Transition component={<div />}} />
```

**Comment by souporserious** [comment]
Fixed here https://github.com/souporserious/react-motion-ui-pack/commit/a656c8dd77a73a13a8aa8f0482208eded1a26473

To use a custom component you would need to pass something like this:

```
class CustomComponent extends Component {
  render() {
    return <div>{this.props.children}</div>
  }
}

OR

const CustomComponent = ({ children }) => (
  <div children={children}/>
)
```

```
<Transition component={CustomComponent}} />
```

Thanks for filing an issue! Sorry about that.
