### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by juliantellez** [souporserious/react-motion-ui-pack#51]
Please update your packages

```
npm ERR! peerinvalid The package react@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-measure@0.3.5 wants react@>0.13.0
npm ERR! peerinvalid Peer react-motion@0.4.4 wants react@>=0.13.2 || ^0.14 || ^15.0.0
npm ERR! peerinvalid Peer react-dom@0.14.8 wants react@^0.14.8
```

**Comment by souporserious** [comment]
This doesn't seem to have to do with this library. I removed `node_modules` and did a clean install and everything seems to work fine. Please provide a better description so I can diagnose the issue.

**Comment by frederickfogerty** [comment]
@souporserious I have submitted a PR to fix this issue. @juliantellez in the future, could you please be a bit more descriptive and potentially submit a PR yourself for such a small issue?
