### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by empz** [souporserious/react-motion-ui-pack#54]
I'm trying to play with this library and so I made a CodePen using the example presented in the readme.

I'm getting a `TypeError: (0 , _elementResizeDetector2.default) is not a function`

Is it a bug or maybe adding the script in the browser is not supported?

Here's the codepen: http://codepen.io/emzero/pen/PzmVmA?editors=0011

**Comment by souporserious** [comment]
Sorry about the wait. You were not including `element-resize-detector` in your pen. Please see here to see it working: http://codepen.io/souporserious/pen/YWaQkk?editors=0011 I updated the README to reflect that dependency, sorry about that.
