### ISSUE TITLE
Props not filtered warning since React 15.2.0

### ISSUE THREAD

**Issue by PEM--** [souporserious/react-motion-ui-pack#55]
When I set up this:

``` js
<Transition component="div" enter={{ opacity: 1 }} leave={{ opacity: 0 }}>
  // ...
</Transition/>
```

I got a warning produced by React since 15.2.0:

```
Warning: Unknown props `enter`, `leave`, `runOnMount`, `onEnter`, `onLeave` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
```

Is there a way to filter props ?

**Comment by transcranial** [comment]
Also, when no wrapper component is specified:

``` js
<Transition component={false} ...
```

a similar warning is produced:

```
Warning: Unknown prop `dimensions` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
```

**Comment by morajabi** [comment]
fix this annoying issue.

**Comment by souporserious** [comment]
@morajabi sorry, I understand it may be annoying, but I'm currently tied up at the moment. PR's are welcome if you would like to fix it.

**Comment by souporserious** [comment]
Fixed https://github.com/souporserious/react-motion-ui-pack/commit/3e95f86fb3ddb6e93fe57e58df9eb3d40bf7684e
