### ISSUE TITLE
Module not found: Error: Cannot resolve module 'ReactMotion'

### ISSUE THREAD

**Issue by dzannotti** [souporserious/react-motion-ui-pack#6]
Getting that error when trying to include this in my project, i suspect it's a typo for react-motion, also i noticed you do `require("React");`, i'm not sure if the capital R on react would cause webpack to include react twice on compilation

**Comment by nkbt** [comment]
`require('react')` should be in lowecase. Webpack can include this twice since is treats `react` and `React` as two different libs.

**Comment by phaistonian** [comment]
Same problem here.

`Module not found: Error: Cannot resolve module 'ReactMotion' in ./node_modules/react-motion-ui-pack/dist`
