### ISSUE TITLE
Remove auto height

### ISSUE THREAD

**Issue by souporserious** [souporserious/react-motion-ui-pack#60]
I've tried to make auto height transitions as easy as I could with little luck so far. It's buggy and it adds a big dependency to this library. It will be removed in the next major release to get the library down to a smaller size. All with the intention of adding it back in at a later time with an option to include it or not.

**Comment by frederickfogerty** [comment]
👍 , animating auto height is so freaking hard.

**Comment by souporserious** [comment]
@frederickfogerty it's stupid how hard it is haha. I think I'm close to a solution with [React Fluid Container](https://github.com/souporserious/react-fluid-container), but until it's solid, I'm keeping it out of here 👉

**Comment by frederickfogerty** [comment]
React Fluid Container looks pretty decent @souporserious, nice work. Haven't used this lib or react-motion for a long time, but it'll be interesting to see how much things have changed when I get back into it.

**Comment by souporserious** [comment]
It is finished https://github.com/souporserious/react-motion-ui-pack/commit/c395345864cbdc5aa73a7bbd7db5347dde0a1acb for now 😛
