### ISSUE TITLE
Duration to animation?

### ISSUE THREAD

**Issue by DarrylD** [souporserious/react-motion-ui-pack#71]
Based on the readme example:
```
<Transition
  component="ul"
  enter={{
    opacity: 1,
  }}
  leave={{
    opacity: 0,
  }}
>  
  { this.state.items.map(item =>
      <li key={item.id}>{item.content}</li>
    )
  }
</Transition>
```

Is there anyway to have that animation go over 4 seconds?

**Comment by souporserious** [comment]
React Motion is physics based so you never define a duration, you set a spring config and let physics take care of the rest. You can find more info [here](https://github.com/chenglou/react-motion#what-does-this-library-try-to-solve) and play around with animations using the [spring parameters chooser](http://chenglou.github.io/react-motion/demos/demo5-spring-parameters-chooser/). Hope that helps :) I was tripped up on not setting a duration at first, but for most UI transitions I don't think you will need to worry about it once you get the hang of it.

**Comment by DarrylD** [comment]
Definitely a different concept to wrap my head. Guess that may be easier than use react-motion directly :)
